### ISSUE TITLE
Credhub CA cert issues

### ISSUE THREAD

**Issue by austinbv** [EngineerBetter/concourse-up#72]
Hey first of all great product!

I am trying to connect to Credhub and seem to get an error around the CA cert being invalid.

```bash
→ credhub l
Error connecting to the targeted API: "Get https://ci.*****.com:8844/info: x509: certificate is not valid for any names, but wanted to match ci.****.com". Please validate your target and retry your request.
```

This is after exporting all the env vars and they are there. Is there something else to do with this certificate?

Things that don't seem to work are logging in and ignoring TLS

```bash
→ credhub l --skip-tls-validation
invalid_token: An I/O error occurred while reading from the JWK Set source: java.security.cert.CertificateException: No name matching ci.***.com found
```

or just executing a command directly 

```bash
credhub set -n /concourse/***/expo-username -v value -t ***
Get https://ci.***.com:8844/info: x509: certificate is not valid for any names, but wanted to match ci.***.com
```

Thanks

**Comment by irbekrm** [comment]
Hi austinbv,
Sorry to hear you had trouble with your deployment.
Could you please tell us:
- what version of of Concourse Up you are using
- have you provided custom tls-cert and tls-key values
- is this a first time deployment

**Comment by austinbv** [comment]
@irbekrm thanks for the fast reply!

I am running concourse v4.2.1 with a wildcard ssl certificate generated by `Let's Encrypt`. I don't think that should matter but who knows.

It's not the first deploy. I had deployed without valid ssl certs for a while but never used credhub. A few weeks after I redeployed with my ssl. That's really it.

Thanks!

**Comment by austinbv** [comment]
@irbekrm 

`0.13.8`

**Comment by irbekrm** [comment]
@austinbv thank you for the detailed info. We are looking at it now and will post once we know more.

**Comment by austinbv** [comment]
So I destroyed and redeployed and credhub is working again _but_ fly cannot connect to ssl on the ci server even with valid certificates

```
○ → fly -t broce login --concourse-url https://ci.broce.com
logging in to team 'main'

could not reach the Concourse server called broce:

    Get https://ci.broce.com/api/v1/info: x509: certificate signed by unknown authority

is the targeted Concourse running? better go catch it lol
```

I can login without ssl which is odd I think.

I left the URL in rather than redacting so you can reproduce. Hopefully this helps

**Comment by austinbv** [comment]
Continuing to update - redeploying now fails. The above issue could be that I didn't give the full certificate chain to concourse, and golang is finicky. When attempting a redeploy with a full certificate chain I get a failure and the certs are not updated

```
  Downloading stemcell... Skipped [Found in local cache] (00:00:00)
  Validating stemcell... Finished (00:00:00)
Finished validating (00:00:01)
No deployment, stemcell or release changes. Skipping deploy.

Succeeded
Fetching info:
  Performing request GET 'https://34.198.83.112:25555/info':
    Performing GET request:
      Retry: Get https://34.198.83.112:25555/info: dial tcp 34.198.83.112:25555: i/o timeout
```

**Comment by austinbv** [comment]
Just continuing to add data - 

Also trying to deploy to a new region with no concourse produces the following error

```bash
Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Creating instance 'bosh/0':
    Waiting until instance is ready:
      Post https://mbus:<redacted>@3.16.74.221:6868/agent: EOF

Exit code 1
exit status 1
```

**Comment by irbekrm** [comment]
@austinbv those last two deployments didn't by any chance say that they are using the previous deployment config?

**Comment by austinbv** [comment]
Not after a destroy no. It did however if I don't do a destroy and try to redeploy.

**Comment by irbekrm** [comment]
Yes, that is what it is supposed to be doing.

Thanks again for providing all the info, we are still looking at it

**Comment by austinbv** [comment]
@irbekrm so a rather interesting change. I have been trying to deploy from my home rather than office network. Thinking that maybe my work blocks some traffic and I get a totally new error both on the redeploy and on a fresh deploy

```bash
Started installing CPI
  Compiling package 'ruby-2.4-r4/0cdc60ed7fdb326e605479e9275346200af30a25'... Finished (00:02:22)
  Compiling package 'bosh_aws_cpi/cd574ff84f900fbb3cb6c302c043e4c2e69941e9'... Finished (00:00:03)
  Installing packages... Finished (00:00:00)
  Rendering job templates... Finished (00:00:00)
  Installing job 'aws_cpi'... Finished (00:00:00)
Finished installing CPI (00:02:26)

Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-aws-xen-hvm-ubuntu-xenial-go_agent/97.12'... Finished (00:00:03)

Started deploying
  Creating VM for instance 'bosh/0' from stemcell 'ami-03282638808c003e2 light'... Finished (00:00:41)
  Waiting for the agent on VM 'i-086588569c286d9e1' to be ready... Finished (00:00:26)
  Creating disk... Finished (00:00:09)
  Attaching disk 'vol-0201742ae9dc8f5ec' to VM 'i-086588569c286d9e1'... Finished (00:00:18)
  Rendering job templates... Finished (00:00:08)
  Compiling package 'ruby-2.4-r4/0cdc60ed7fdb326e605479e9275346200af30a25'... Skipped [Package already compiled] (00:00:19)
  Compiling package 'mysql/898f50dde093c366a644964ccb308a5281c226de'... Skipped [Package already compiled] (00:00:21)
  Compiling package 'libpq/0d118c5dd7928f8c057de40b5f8f2d7dde48f6c7'... Skipped [Package already compiled] (00:00:02)
  Compiling package 'bpm-runc/c0b41921c5063378870a7c8867c6dc1aa84e7d85'... Skipped [Package already compiled] (00:00:10)
  Compiling package 'golang/27413c6b5a88ea20a24a9eed74d4b090b7b88331'... Skipped [Package already compiled] (00:11:42)
  Compiling package 'ruby-2.4-r4/0cdc60ed7fdb326e605479e9275346200af30a25'...panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x106b4f3]

goroutine 615 [running]:
io.copyBuffer(0x1bfdd00, 0xc420459480, 0x0, 0x0, 0xc420590000, 0x8000, 0x8000, 0xc420459480, 0xc420459480, 0x19cb9c0)
	/usr/local/go/src/io/io.go:400 +0x143
io.Copy(0x1bfdd00, 0xc420459480, 0x0, 0x0, 0xc420489da0, 0xc420489d78, 0x1010288)
	/usr/local/go/src/io/io.go:362 +0x5a
net.genericReadFrom(0x1bfc140, 0xc4205780f8, 0x0, 0x0, 0xc42027bbf0, 0x1050950, 0xc420489de8)
	/usr/local/go/src/net/net.go:597 +0x84
net.(*TCPConn).readFrom(0xc4205780f8, 0x0, 0x0, 0xc420489e08, 0x100e04d, 0x1998080)
	/usr/local/go/src/net/tcpsock_posix.go:51 +0x4d
net.(*TCPConn).ReadFrom(0xc4205780f8, 0x0, 0x0, 0x25dd2e8, 0xc4205780f8, 0xc42001c001)
	/usr/local/go/src/net/tcpsock.go:103 +0x5f
io.copyBuffer(0x1bfc140, 0xc4205780f8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1a9ff80, 0xc420216d00, 0x1bfc140)
	/usr/local/go/src/io/io.go:386 +0x31a
io.Copy(0x1bfc140, 0xc4205780f8, 0x0, 0x0, 0x0, 0xc420466048, 0xc420466040)
	/usr/local/go/src/io/io.go:362 +0x5a
github.com/cloudfoundry/bosh-cli/deployment/sshtunnel.(*sshTunnel).Start.func3(0x1c0bfa0, 0xc4205780f8, 0x0, 0x0, 0xc42002f220, 0xc4202e81e0)
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/deployment/sshtunnel/ssh_tunnel.go:85 +0xc3
created by github.com/cloudfoundry/bosh-cli/deployment/sshtunnel.(*sshTunnel).Start
	/tmp/build/a9832f70/gopath/src/github.com/cloudfoundry/bosh-cli/deployment/sshtunnel/ssh_tunnel.go:84 +0x314
exit status 2
```

I will dig in more but wanted to add it for context

**Comment by austinbv** [comment]
This is gonna drive you crazy but after a destroy and a redeploy I have a working install with the latest release of concourse-up

If you want any extra info about what's happening email me austin@broce.com

**Comment by austinbv** [comment]
I will close - I have a new one for us :)
